name: Release

on:
  workflow_dispatch:
  push:
    paths:
      - .version

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Read .version file
      id: version
      run: echo "::set-output name=version::$(cat .github/.version)"

    - name: change version numbers
      run: | 
       sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' Installer.bat
       grep Installer.bat -e ${{ steps.version.outputs.version }}
       sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' MC-Launcher.bat
       grep MC-Launcher.bat -e ${{ steps.version.outputs.version }}
       sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' Mod-Installer.bat
       grep Mod-Installer.bat -e ${{ steps.version.outputs.version }}

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          Installer.bat
          MC-Launcher.bat
          Mod-Installer.bat
          Installer.ico
          Launcher.ico
          Mod-Installer.ico

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.event_name != 'pull_request'
      with:
        prerelease: false
        repo_token: ${{ github.token }}
        title: ${{ steps.version.outputs.version }}
        automatic_release_tag: ${{ steps.version.outputs.version }}
        files: |
          Installer.bat
          MC-Launcher.bat
          Mod-Installer.bat
          Installer.ico
          Launcher.ico
          Mod-Installer.ico
